//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class CaseViewModel
    {
        public int CaseID { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        [StringLength(24, MinimumLength = 6, ErrorMessage = "Must be between 6-24.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Can't be empty! (dd.mm.yyyy)")]
        public Nullable<System.DateTime> SymptomsBegan { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        [StringLength(512, MinimumLength = 64, ErrorMessage = "Must be between 64-512.")]
        public string CurrentMedications { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        [StringLength(512, MinimumLength = 64, ErrorMessage = "Must be between 64-512.")]
        public string BodySystemsAffected { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        [StringLength(512, MinimumLength = 64, ErrorMessage = "Must be between 64-512.")]
        public string SymptomsDetail { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        [StringLength(512, MinimumLength = 64, ErrorMessage = "Must be between 64-512.")]
        public string MedicalHistory { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        [StringLength(512, MinimumLength = 64, ErrorMessage = "Must be between 64-512.")]
        public string PersonalStruggle { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string User { get; set; }
    }
}
